---
- name: Install Filebeat and Metricbeat
  hosts: webservers
  become: yes
  tasks:
  - name: Download metricbeat package
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.$  - name: Install metricbeat package
    command: dpkg -i metricbeat-7.4.0-amd64.deb
  - name: copy over metricbeat configuration
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml
      mode: '0644'
  - name: Enable and Configure System Module
    command: metricbeat modules enable system
  - name: Setup metricbeat
    command: metricbeat setup
  - name: Start metricbeat service
    command: service metricbeat start

